development:
  payjp_secret_key: <%= ENV["PAYJP_SECRET_KEY"] %>
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>

production:
  payjp_secret_key: <%= ENV["PAYJP_SECRET_KEY"] %>
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>